### ISSUE TITLE
 cnt cannot be used as a standard to perform logout

### ISSUE THREAD

**Issue by zhucan** [kubernetes-csi/csi-driver-iscsi#19]
https://github.com/kubernetes-csi/csi-driver-iscsi/blob/12d5f01a9ec97725ba254881f6b4f9d39605ed5e/pkg/iscsi/iscsi_util.go#L83

If there is only one worker node, when the pod rebuilding, the NodePublishVolume will be called first, and then the NodeUnpublishVolume will be called after the NodePublishVolume. Because of every times the pod rebuilding the targetPath is different, We cant't  judge whether the volume is used, when  the NodeUnpublishVolume is called, the cnt is always 1, it will logout, the connection between volume and pod will lost.

@saad-ali

**Comment by j-griffith** [comment]
I'll have to take a closer look at this again, I'm not sure why the target-path should be different each time here, and if it is; it's unclear to me how one would determine duplicate device mounts?

**Comment by zhucan** [comment]
If the kind of the pod is deployment, when the pod rebuilding the target-path is different, because of the uuid of the pod is different.  The examples of the target-path: "/var/lib/kubelet/pods/e343ee06-1b21-4037-a509-9224df45fbd0/volumes/kubernetes.io~csi/pvc-78f9fa64-e0a5-4253-8e0a-e11dc9fe362f/mount"

It's possible for that one device corresponds to two targetPath when the deployment rebuilding on the same node.
