### ISSUE TITLE
 Will the host not get stuck when restarting with iscsi device and not mount with _netdev?

### ISSUE THREAD

**Issue by zhucan** [kubernetes-csi/csi-driver-iscsi#20]
For example:

If we use iscsi device for a pod, when the host rebooting with pod, Won't it get hangs？

@j-griffith @saad-ali

**Comment by zhucan** [comment]
@saad-ali we should mount iscsi device with "_netdev" automatically.

**Comment by j-griffith** [comment]
@zhucan can you describe a bit more; perhaps share a bit more detail around your configuration and test case?

**Comment by zhucan** [comment]
@j-griffith Can you take a look at this? Maybe I can solve this issue.
