### ISSUE TITLE
Use csi-lib-iscsi?

### ISSUE THREAD

**Issue by msau42** [kubernetes-csi/csi-driver-iscsi#5]
@j-griffith can the iscsi lib be used for this driver?

**Comment by msau42** [comment]
https://github.com/kubernetes-csi/csi-lib-iscsi

**Comment by j-griffith** [comment]
Yes, I have a couple ideas to add the proven routines from this iscsi_util file into the lib, I'll start working it up this week with @prateekpandey14 and we can get things ready to go.
