### ISSUE TITLE
installation procedure

### ISSUE THREAD

**Issue by paullaffitte** [kubernetes-csi/csi-driver-iscsi#63]
Hello,

I'm trying to install this plugin on one of my k8s development cluster. But I'm facing several issues :

- The image `iscsiplugin:latest` doesn't exists, so I have to build and push it before updating `.yaml` files in accordance.
- I got the error `MountVolume.SetUp failed for volume "lib-modules" : hostPath type check failed: /lib/modules is not a directory` while describing one of the pods, even if the folder `/lib/modules` exists on the host. Removing `type: Directory` in the volume definition fixes the issue.
- I got the error `iscsid: Can not bind IPC socket` from `iscsid -f` command. I tried to add `hostIPC: true` to the daemonset's pods spec but it doesn't seems to fix anything. (EDIT: uninstalling open-iscsi package on the host fixed it, which is actually the expected behavior).

I'm not sure if those issues are real issues or if they are coming from me not using the plugin in the proper way. Anyway, I think this repository is missing some installation instructions and that the installation experience could be improved (for exemple by using a helm chart, or having the image publicly available on docker hub).

**Comment by humblec** [comment]
@paullaffitte indeed , many hiccups to get this working and I was working towards the initial release [1] , however I was able to deploy it and use to a good extent in my experiments and get deployment , mount...etc working https://github.com/kubernetes-csi/csi-driver-iscsi/pull/45#issuecomment-853639620 , eventhough some of the changes are in my local repo yet, you could try to deploy this via [2] 

[1] https://github.com/kubernetes-csi/csi-driver-iscsi/issues/4
[2] https://github.com/kubernetes-csi/csi-driver-iscsi/pull/45/files

**Comment by paullaffitte** [comment]
With some little modifications I was able to use your csi-node with my csi-controller and I confirm that it's working properly.

**Comment by humblec** [comment]
@paullaffitte now we have the instllation process in place .. so I believe this issue can be closed.. if you face any issues, please feel free to open a new one.
