### ISSUE TITLE
csc node publish  command fails : unexpected end of JSON input

### ISSUE THREAD

**Issue by sanjeevshar** [kubernetes-csi/csi-driver-iscsi#9]
I tried to test driver using instructions in README but it fails.  Please scroll to the end to see Error message on the driver side. How to I get more details about the error?

test@dsib1093:~/go/bin$ csc node publish -e tcp://127.0.0.1:10000 -l debug  --attrib targetPortal=$ISCSI_TARGET,iqn=$IQN,lun=$LUN  iscsitestvol
DEBU[0000] assigned the root context
DEBU[0000] mounting volume                               request="{iscsitestvol map[]   <nil> false map[] map[iqn:iqn.1994-05.com.Max:CLFN3:0359-1F24 lun:0 targetPortal:192.168.208.159] {} [] 0}"
DEBU[0000] parsed endpoint info                          addr="127.0.0.1:10000" proto=tcp timeout=1m0s
unexpected end of JSON input

Driver side:
I0322 09:23:13.424043  320504 utils.go:97] GRPC call: /csi.v1.Node/NodePublishVolume
I0322 09:23:13.424062  320504 utils.go:98] GRPC request: {"volume_context":{"iqn":"iqn.1994-05.com.Max:CLFN3:0359-1F24","lun":"1","targetPortal":"192.168.208.159"},"volume_id":"iscsitestvol"}
E0322 09:23:13.424527  320504 utils.go:101] GRPC error: rpc error: code = Internal desc = unexpected end of JSON input

**Comment by yeahdongcn** [comment]
I have encountered the same issue recently when publishing a volume.
@sanjeevshar did you resolve this problem?
