### ISSUE TITLE
iscsiplugin image tag v0.1.0 was pushed again overwriting the existing image tag

### ISSUE THREAD

**Issue by mauriciopoppe** [kubernetes-csi/csi-driver-iscsi#97]
**What happened**:
In https://github.com/kubernetes/k8s.io/pull/3345#discussion_r798853559 we found out that the v0.1.0 image was overwritten, once an image is released it should be considered immutable and we shouldn't overwrite the tag, if there are critical bug fixes I think we should bump the image.

I'm not sure about the fix, we could:
- ask the owner of k8s.gcr.io to manually remove the existing v0.1.0 image (I'm not sure if this is allowed)
- retag the v0.1.0 canary in sig-storage-staging to point to the existing tag sha256:31117074c183242b223340f2fc0f886243e97c6cb1a83d98cfb00a69d1746697 and rerun the image promoter again

/cc @msau42

**Comment by humblec** [comment]
@msau42 yeah, it shouldnt have been overwritten eventhough both hashes [1] are same code .

"sha256:31117074c183242b223340f2fc0f886243e97c6cb1a83d98cfb00a69d1746697"
 "sha256:8ff2016fd563f0365ccf6ad4ab09f09a1941cbede5c62c5692e95589c0ed41de" 

Can I remove the first or existing hash in a PR and quickly a followup PR with other hash? I believe it should be fine as max it could cause a small disruption if some one pull in between?

**Comment by humblec** [comment]
https://github.com/kubernetes/k8s.io/pull/3351 remove the first hash. If this is not allowed, the second method retagging the existing hash to ` v0.1.0 canary` as @mauriciopoppe mentioned, and can run the promoter again..

**Comment by msau42** [comment]
Issue has been fixing by modifying the tag in the staging repo to match the hash that was promoted.
